<?php

include APPROOT . "/views/inc/header.php";
include APPROOT . "/views/inc/nav.php";

?>

<style>
    .text-justify {
        text-align: justify !important;
    }
</style>
<main>
    <div class="container py-4">
        <div class="col-lg-12 ">
            <h1 class="f-26 w-700 text-primary text-center">PRIVACY POLICY</h1>
            <p class="text mt-4 ">Effective date: 2023-06-21</p>
            <h3 class="f-18 w-700 mt-5 mb-3">1. Introduction</h3>

            <p>
                Welcome to Kwepilecorp.

            </p>
            <p class="text text-justify">
                Kwepilecorp (“us”, “we”, or “our”) operates Inscripchat.com
                (hereinafter referred to as “Service”).
            </p>
            <p class="text text-justify">
                Our Privacy Policy governs your visit to Inscripchat.com, and explains
                how we collect, safeguard and disclose information that results from
                your use of our Service.
            </p>
            <p class="text text-justify">
                We use your data to provide and improve Service. By using Service, you
                agree to the collection and use of information in accordance with this
                policy. Unless otherwise defined in this Privacy Policy, the terms used in
                this Privacy Policy have the same meanings as in our Terms and
                Conditions.
            </p>
            <p class="text text-justify">
                Our Terms and Conditions (<b>“Terms”</b>) govern all use of our Service and
                together with the Privacy Policy constitutes your agreement with us
                (<b>“agreement”</b>).
            </p>

            <h3 class="f-18 w-700 mt-5 mb-3">2. Definitions
            </h3>

            <p class="text text-justify">
                <b>SERVICE</b> means the Inscripchat.com website operated by Kwepilecorp.
            </p>
            <p class="text text-justify">
                <b>PERSONAL DATA</b> means data about a living individual who can be
                identified from those data (or from those and other information either in
                our possession or likely to come into our possession).
            </p>
            <p class="text text-justify">
                <b>USAGE DATA</b> is data collected automatically either generated by the use
                of Service or from Service infrastructure itself (for example, the
                duration of a page visit).
            </p>
            <p class="text text-justify">

                <b>COOKIES </b>are small files stored on your device (computer or mobile
                device).
            </p>
            <p class="text text-justify">
                <b>DATA CONTROLLER</b> means a natural or legal person who (either alone
                or jointly or in common with other persons) determines the purposes for
                which and the manner in which any personal data are, or are to be,
                processed. For the purpose of this Privacy Policy, we are a Data
                Controller of your data.
            </p>
            <p class="text text-justify">
                <b>DATA PROCESSORS</b> (OR SERVICE PROVIDERS) means any natural or
                legal person who processes the data on behalf of the Data Controller. We
                may use the services of various Service Providers in order to process
                your data more effectively.
            </p>
            <p class="text text-justify">
                <b>DATA SUBJECT</b> is any living individual who is the subject of Personal
                Data.
            </p>
            <p class="text text-justify">
                <b>THE USER</b> is the individual using our Service. The User corresponds to
                the Data Subject, who is the subject of Personal Data.
            </p>



            <h3 class="f-18 w-700 mt-5 mb-3">4. Types of Data Collected
            </h3>

            <p class="text text-justify">

                <b>Personal Data</b><br>
                While using our Service, we may ask you to provide us with certain
                personally identifiable information that can be used to contact or
                identify you (“Personal Data”). Personally identifiable information may
                include, but is not limited to:

                <br><br>
                0.1. Email address<br><br>
                0.2. First name and last name<br><br>
                0.3. Phone number<br><br>
                0.4. Address, Country, State, Province, ZIP/Postal code, City<br><br>
                0.5. Cookies and Usage Data<br><br>


                We may use your Personal Data to contact you with newsletters,
                marketing or promotional materials and other information that may be
                of interest to you. You may opt out of receiving any, or all, of these
                communications from us by following the unsubscribe link.
            </p>
            <br>


            <p class="text text-justify">
                <b>Usage Data
                </b><br><br>
                We may also collect information that your browser sends whenever you
                visit our Service or when you access Service by or through any device
                (“Usage Data”).

            </p>
            <p class="text text-justify">
                This Usage Data may include information such as your computer’s
                Internet Protocol address (e.g. IP address), browser type, browser
                version, the pages of our Service that you visit, the time and date of your
                visit, the time spent on those pages, unique device identifiers and other
                diagnostic data.
            </p>
            <p class="text text-justify">
                When you access Service with a device, this Usage Data may include
                information such as the type of device you use, your device unique ID,
                the IP address of your device, your device operating system, the type of
                Internet browser you use, unique device identifiers and other diagnostic
                data.
            </p>


            <p class="text text-justify">
                <b>Tracking Cookies Data </b><br><br>
                We use cookies and similar tracking technologies to track the activity on
                our Service and we hold certain information.
            </p>

            <p class="text text-justify">
                Cookies are files with a small amount of data which may include an
                anonymous unique identifier. Cookies are sent to your browser from a
                website and stored on your device. Other tracking technologies are also
                used such as beacons, tags and scripts to collect and track information
                and to improve and analyze our Service.
            </p>

            <p class="text text-justify">
                You can instruct your browser to refuse all cookies or to indicate when a
                cookie is being sent. However, if you do not accept cookies, you may not
                be able to use some portions of our Service.
            </p>

            <p class="text text-justify">
                Examples of Cookies we use:<br><br>
                0.1. <b>Session Cookies:</b> We use Session Cookies to operate our Service.<br><br>
                0.2. <b>Preference Cookies:</b> We use Preference Cookies to remember your
                preferences and various settings.<br><br>
                0.3. <b>Security Cookies:</b> We use Security Cookies for security purposes.<br><br>
                0.4. <b>Advertising Cookies:</b> Advertising Cookies are used to serve you
                with advertisements that may be relevant to you and your interests.
            </p>

            <p class="text text-justify">
                <br>
                <b>Other Data </b><br><br>
                While using our Service, we may also collect the following information:
                sex, age, date of birth, place of birth, passport details, citizenship,
                registration at place of residence and actual address, telephone number
                (work, mobile), details of documents on education, qualification,
                professional training, employment agreements, <a href="https://policymaker.io/non-disclosure-agreement/">NDA agreements</a>,
                information on bonuses and compensation, information on marital
                status, family members, social security (or other taxpayer identification)
                number, office location and other data.
            </p>


            <h3 class="f-18 w-700 mt-5 mb-3 ">5. Use of Data
            </h3>
            <p class="text text-justify">
                Kwepilecorp uses the collected data for various purposes:<br><br>
                0.1. to provide and maintain our Service;<br><br>
                0.2. to notify you about changes to our Service;<br><br>
                0.3. to allow you to participate in interactive features of our Service
                when you choose to do so;<br><br>
                0.4. to provide customer support;<br><br>
                0.5. to gather analysis or valuable information so that we can improve
                our Service;<br><br>
                0.6. to monitor the usage of our Service;<br><br>
                0.7. to detect, prevent and address technical issues;<br><br>
                0.8. to fulfil any other purpose for which you provide it;<br><br>
                0.9. to carry out our obligations and enforce our rights arising from any
                contracts entered into between you and us, including for billing and
                collection;<br><br>
                0.10. to provide you with notices about your account and/or
                subscription, including expiration and renewal notices, emailinstructions, etc.;<br><br>
                0.11. to provide you with news, special offers and general information
                about other goods, services and events which we offer that are similar to
                those that you have already purchased or enquired about unless you have
                opted not to receive such information;<br><br>
                0.12. in any other way we may describe when you provide the
                information;<br><br>
                0.13. for any other purpose with your consent.
            </p>


            <h3 class="f-18 w-700 mt-5 mb-3">6. Retention of Data
            </h3>

            <p class="text text-justify">
                We will retain your Personal Data only for as long as is necessary for the
                purposes set out in this Privacy Policy. We will retain and use your
                Personal Data to the extent necessary to comply with our legal
                obligations (for example, if we are required to retain your data to
                comply with applicable laws), resolve disputes, and enforce our legal
                agreements and policies.<br><br>
                We will also retain Usage Data for internal analysis purposes. Usage
                Data is generally retained for a shorter period, except when this data is
                used to strengthen the security or to improve the functionality of our
                Service, or we are legally obligated to retain this data for longer time
                periods.
            </p>


            <h3 class="f-18 w-700 mt-5 mb-3">7. Transfer of Data

            </h3>

            <p class="text text-justify">
                Your information, including Personal Data, may be transferred to – and
                maintained on – computers located outside of your state, province,
                country or other governmental jurisdiction where the data protection
                laws may differ from those of your jurisdiction.<br><br>
                If you are located outside United States of America and choose to provide
                information to us, please note that we transfer the data, including
                Personal Data, to United States of America and process it there.
                Your consent to this Privacy Policy followed by your submission of such
                information represents your agreement to that transfer.<br><br>
                Kwepilecorp will take all the steps reasonably necessary to ensure that
                your data is treated securely and in accordance with this Privacy Policy
                and no transfer of your Personal Data will take place to an organisation
                or a country unless there are adequate controls in place including the
                security of your data and other personal information.
            </p>
            <h3 class="f-18 w-700 mt-5 mb-3">8. Disclosure of Data
            </h3>

            <p class="text text-justify">
                We may disclose personal information that we collect, or you provide:
                <br><br>
                0.1. <b>Disclosure for Law Enforcement.</b><br><br>
                Under certain circumstances, we may be required to disclose your
                Personal Data if required to do so by law or in response to valid requests
                by public authorities.<br><br>
                0.2. <b>Business Transaction.</b><br><br>
                If we or our subsidiaries are involved in a merger, acquisition or asset
                sale, your Personal Data may be transferred.<br><br>
                0.3. <b>Other cases. We may disclose your information also:</b><br><br>
                0.3.1. to our subsidiaries and affiliates;<br><br>
                0.3.2. to contractors, service providers, and other third parties we use to
                support our business;<br><br>
                0.3.3. to fulfill the purpose for which you provide it;<br><br>
                0.3.4. for the purpose of including your company’s logo on our website;
                0.3.5. for any other purpose disclosed by us when you provide the
                information;<br><br>
                0.3.6. with your consent in any other cases;<br><br>
                0.3.7. if we believe disclosure is necessary or appropriate to protect the
                rights, property, or safety of the Company, our customers, or others.
            </p>


            <h3 class="f-18 w-700 mt-5 mb-3">9. Security of Data

            </h3>
            <p class="text text-justify">
                The security of your data is important to us but remember that no
                method of transmission over the Internet or method of electronic storage
                is 100% secure. While we strive to use commercially acceptable means
                to protect your Personal Data, we cannot guarantee its absolute security.
            </p>
            <h3 class="f-18 w-700 mt-5 mb-3">10. Your Data Protection Rights Under General Data Protection
                10. Regulation (GDPR)
            </h3>

            <p class="text text-justify">
                If you are a resident of the European Union (EU) and European Economic
                Area (EEA), you have certain data protection rights, covered by GDPR.<br><br>
                We aim to take reasonable steps to allow you to correct, amend, delete,
                or limit the use of your Personal Data.<br><br>
                If you wish to be informed what Personal Data we hold about you and if
                you want it to be removed from our systems, please email us at
                <b>info@Inscripchat.com.</b><br><br>
                In certain circumstances, you have the following data protection rights:
                0.1. the right to access, update or to delete the information we have on
                you;<br><br>
                0.2. the right of rectification. You have the right to have your
                information rectified if that information is inaccurate or incomplete;<br><br>
                0.3. the right to object. You have the right to object to our processing of
                your Personal Data;<br><br>
                0.4. the right of restriction. You have the right to request that we restrict
                the processing of your personal information;<br><br>
                0.5. the right to data portability. You have the right to be provided with a
                copy of your Personal Data in a structured, machine-readable and
                commonly used format;<br><br>
                0.6. the right to withdraw consent. You also have the right to withdraw
                your consent at any time where we rely on your consent to process your
                personal information;<br><br>
                Please note that we may ask you to verify your identity before
                responding to such requests. Please note, we may not able to provide
                Service without some necessary data.<br><br>
                You have the right to complain to a Data Protection Authority about our
                collection and use of your Personal Data. For more information, please
                contact your local data protection authority in the European Economic
                Area (EEA).
            </p>


            <h3 class="f-18 w-700 mt-5 mb-3"> 11. Analytics
            </h3>
            <p class="text text-justify">
                We may use third-party Service Providers to monitor and analyze the use
                of our Service.
            </p>

            <h3 class="f-18 w-700 mt-5 mb-3"> 12. CI/CD tools

            </h3>

            <p class="text text-justify">
                We may use third-party Service Providers to automate the development
                process of our Service.
            </p>

            <h3 class="f-18 w-700 mt-5 mb-3">
                13. Advertising
            </h3>
            <p class="text text-justify">
                We may use third-party Service Providers to show advertisements to you
                to help support and maintain our Service.
            </p>

            <h3 class="f-18 w-700 mt-5 mb-3">
                14. Links to Other Sites

            </h3>

            <p class="text text-justify">
                Our Service may contain links to other sites that are not operated by us.
                If you click a third party link, you will be directed to that third party’s
                site. We strongly advise you to review the <a href="https://policymaker.io/privacy-policy/">Privacy Policy</a> of every site
                you visit.<br><br>
                We have no control over and assume no responsibility for the content,
                privacy policies or practices of any third party sites or services.<br><br>
                For example, the outlined privacy policy has been made using
                <a href="https://policymaker.io/">PolicyMaker.io</a>, a free tool that helps create high-quality legal
                documents. PolicyMaker’s <a href="https://policymaker.io/privacy-policy/">privacy policy generator </a>is an easy-to-use tool
                for creating a <a href="https://policymaker.io/blog-privacy-policy/">privacy policy for blog</a>, website, e-commerce store or
                mobile app.
            </p>
            <h3 class="f-18 w-700 mt-5 mb-3">
                15. Children’s Privacy
            </h3>

            <p class="text text-justify">
                Our Services are not intended for use by children under the age of 18
                (<b>“Child”</b> or <b> “Children”</b>).<br><br>
                We do not knowingly collect personally identifiable information from
                Children under 18. If you become aware that a Child has provided us
                with Personal Data, please contact us. If we become aware that we have
                collected Personal Data from Children without verification of parental
                consent, we take steps to remove that information from our servers.
            </p>

            <h3 class="f-18 w-700 mt-5 mb-3">
                16. Changes to This Privacy Policy
            </h3>

            <p class="text text-justify">
                We may update our Privacy Policy from time to time. We will notify you
                of any changes by posting the new Privacy Policy on this page.<br><br>
                We will let you know via email and/or a prominent notice on our Service,
                prior to the change becoming effective and update “effective date” at the
                top of this Privacy Policy.<br><br>
                You are advised to review this Privacy Policy periodically for any
                changes. Changes to this Privacy Policy are effective when they are
                posted on this page.
            </p>

            <h3 class="f-18 w-700 mt-5 mb-3">
                17. Contact Us
            </h3>

            <p class="text text-justify">
                If you have any questions about this Privacy Policy, please contact us by
                email: <b>policyinfo@Inscripchat.com.</b>
            </p>

        </div>



    </div>


</main>

<?php

include APPROOT . "/views/inc/footer.php";

?>